### ISSUE TITLE
Similarity calculations appears to miss the last target

### ISSUE THREAD

**Issue by rahulnair23** [IBM/Hestia-OOD#12]
**Describe the bug**
When computing similarity, the returned data frame misses computing similarities to the last target.

**To Reproduce**
Minimally, running the following snippet
```
import pandas as pd
from hestia.similarity import calculate_similarity

smiles = ['[H][C]1=[N][C]2=[C]([O][C]([H])([H])[C]3([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]3([H])[H])[N]=[C]([N]([H])[C]3=[C]([H])[C]([H])=[C]([H])[C]([Br])=[C]3[H])[N]=[C]2[N]1[H]', '[H][C]1=[N][C]2=[C]([O][C]([H])([H])[C]3([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]([H])([H])[C]3([H])[H])[N]=[C]([N]([H])[C]3=[C]([H])[C]([H])=[C]([H])[C]([H])=[C]3[H])[N]=[C]2[N]1[H]', '[H]c1c(c(c(c(c1[H])Cl)[H])N([H])c2nc3c(c(n2)OC([H])([H])C4(C(C(C(C(C4([H])[H])([H])[H])([H])[H])([H])[H])([H])[H])[H])N=C(N3[H])[H])[H]', ]

df = pd.DataFrame({'smiles': smiles})
sim_df = calculate_similarity(df, data_type='small_molecule', similarity_metric='fingerprint', field_name='smiles')
print(f"Max index: Query: {sim_df['query'].max()}, Target: {sim_df.target.max()}. ")
```
returns `Max index: Query: 2, Target: 1. `

**Expected behavior**
Should return `Max index: Query: 2, Target: 2.` (i.e. should return the full matrix). 

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] NA
 - Version [e.g. 22] 14.5

**Additional context**
None.

**Comment by RaulFD-creator** [comment]
Hi @rahulnair23, thanks for pointing this bug out. It has been fixed in the latest pull request #13
